const ActionTypes = {
	ADD_TODO: 'ADD_TODO',
	EDIT_TODO: 'EDIT_TODO',
	CANCEL_EDIT: 'CANCEL_EDIT',
	UPDATE_TODO: 'UPDATE_TODO',
	DELETE_TODO: 'DELETE_TODO',
	TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',
	TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
	SHOW_SHARE: 'SHOW_SHARE',
	HIDE_SHARE: 'HIDE_SHARE'
};

export default ActionTypes;